### ISSUE TITLE
Electerm 1.12.7 deb not work on ubuntu 18.04 64bit

### ISSUE THREAD

**Issue by pincopallopino** [electerm/electerm#2089]
i'ive installe deb of Electerm 1.12.7 from https://electerm.html5beta.com but the application doesn't start correctly and keep hanging on loading screen.

if i start from terminal i get the following errors:

federico@federico-Latitude-5590:~$ electerm 
17:16:18 debug › electerm start
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/electerm/resources/app.asar/server/session.js
- /opt/electerm/resources/app.asar/server/dispatch-center.js
- /opt/electerm/resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/electerm/resources/app.asar/server/session.js',
    '/opt/electerm/resources/app.asar/server/dispatch-center.js',
    '/opt/electerm/resources/app.asar/server/server.js'
  ]
}
/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.OpFLJX)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

**Comment by zxdong262** [comment]
Can you try `sudo apt install -f`, if this do not work, you may try install from snap, could be something related to OS, as I tested in ubuntu 20.04 it works.
